"""Alembic 마이그레이션이 모델·소재 목록과 맞는지 확인합니다.

- head 까지 올린 스키마가 database.py 모델과 같다(`alembic check` 와 같은 검사).
  모델을 고치고 리비전을 안 더하면 여기서 실패한다.
- 시드 리비전이 넣은 소재가 init_data.MATERIAL_SEEDS 와 같다. 목록을 고치고
  리비전을 안 더하면(또는 그 반대) 여기서 실패한다.
- downgrade base 로 모두 되돌리고 다시 올릴 수 있다.
- DB 가 최신 리비전이 아니면 서버가 시작하지 않는다(마이그레이션을 빼먹은 배포).
"""

import json

import pytest
from alembic import command
from fastapi.testclient import TestClient
from sqlalchemy import inspect, text

import database
import init_data
import main

# 기준선(develop 표 4개) 리비전. 시드 리비전은 이 바로 위에 있다.
BASELINE_REVISION = "98b9938f3cd5"


def test_upgrade_head_matches_models(alembic_config):
    command.upgrade(alembic_config, "head")

    # 차이가 있으면 AutogenerateDiffsDetected 를 던진다.
    command.check(alembic_config)


def test_seed_revision_matches_init_data(alembic_config):
    command.upgrade(alembic_config, "head")

    with database.engine.connect() as connection:
        rows = connection.execute(
            text(
                "SELECT name_ko, name_en, aliases, carbon_factor, unit "
                "FROM materials ORDER BY id"
            )
        ).all()

    actual = [
        (name_ko, name_en, json.loads(aliases), carbon_factor, unit)
        for name_ko, name_en, aliases, carbon_factor, unit in rows
    ]
    expected = [
        (
            seed["name_ko"],
            seed["name_en"],
            seed["aliases"],
            seed["carbon_factor"],
            init_data.TEXTILE_UNIT,
        )
        for seed in init_data.MATERIAL_SEEDS
    ]
    assert actual == expected, (
        "init_data.MATERIAL_SEEDS 와 마이그레이션이 넣은 소재가 다릅니다. "
        "목록을 고쳤다면 새 리비전(UPDATE·INSERT)을 더하세요."
    )


def test_downgrade_base_then_upgrade_again(alembic_config):
    command.upgrade(alembic_config, "head")

    # 기준선까지만 되돌리면(시드 리비전과 그 위) 표는 남고 소재만 빠진다.
    command.downgrade(alembic_config, BASELINE_REVISION)
    with database.engine.connect() as connection:
        assert connection.execute(text("SELECT count(*) FROM materials")).scalar() == 0

    command.downgrade(alembic_config, "base")

    assert set(inspect(database.engine).get_table_names()) == {"alembic_version"}

    command.upgrade(alembic_config, "head")
    command.check(alembic_config)


@pytest.mark.parametrize("target", [None, BASELINE_REVISION])
def test_server_refuses_to_start_unless_schema_is_head(alembic_config, target):
    # None = 아무 리비전도 적용 안 한 빈 DB, BASELINE = 시드 리비전을 빼먹은 DB
    if target is not None:
        command.upgrade(alembic_config, target)

    with pytest.raises(RuntimeError, match="alembic upgrade head"):
        with TestClient(main.app):
            pass

    command.upgrade(alembic_config, "head")
    with TestClient(main.app) as client:
        assert client.get("/materials").status_code == 200
