CLASS_TO_KO = {
    "30C": "30도 물세탁",
    "40C": "40도 물세탁",
    "50C": "50도 물세탁",
    "60C": "60도 물세탁",
    "70C": "70도 물세탁",
    "95C": "95도 물세탁",
    "DN_bleach": "표백 금지",
    "DN_dry": "건조 금지",
    "DN_dry_clean": "드라이클리닝 금지",
    "DN_iron": "다림질 금지",
    "DN_steam": "스팀 금지",
    "DN_tumble_dry": "건조기 사용 금지",
    "DN_wash": "물세탁 금지",
    "DN_wet_clean": "웨트클리닝 금지",
    "DN_wring": "비틀어 짜기 금지",
    "bleach": "표백 가능",
    "chlorine_bleach": "염소계 표백 가능",
    "non_chlorine_bleach": "비염소계 표백 가능",
    "drip_dry": "물방울 건조",
    "drip_dry_in_shade": "그늘에서 물방울 건조",
    "dry_flat": "평평하게 펴서 건조",
    "line_dry": "걸어서 건조",
    "line_dry_in_shade": "그늘에서 걸어서 건조",
    "natural_dry": "자연 건조",
    "shade_dry": "그늘 건조",
    "dry_clean": "드라이클리닝 가능",
    "dry_clean_any_solvent": "모든 용제 드라이클리닝 가능",
    "dry_clean_any_solvent_except_trichloroethylene": "트리클로로에틸렌 제외 용제 드라이클리닝 가능",
    "dry_clean_low_heat": "저온 드라이클리닝",
    "dry_clean_no_steam": "스팀 없이 드라이클리닝",
    "dry_clean_petrol_only": "석유계 용제 드라이클리닝",
    "dry_clean_reduced_moisture": "저수분 드라이클리닝",
    "dry_clean_short_cycle": "짧은 코스 드라이클리닝",
    "hand_wash": "손세탁",
    "machine_wash_delicate": "약한 코스 기계세탁",
    "machine_wash_normal": "표준 코스 기계세탁",
    "machine_wash_permanent_press": "구김방지 코스 기계세탁",
    "iron": "다림질 가능",
    "iron_low": "저온 다림질 가능",
    "iron_medium": "중온 다림질 가능",
    "iron_high": "고온 다림질 가능",
    "steam": "스팀 가능",
    "tumble_dry_high": "고온 건조기 가능",
    "tumble_dry_low": "저온 건조기 가능",
    "tumble_dry_medium": "중온 건조기 가능",
    "tumble_dry_no_heat": "무열 건조 가능",
    "tumble_dry_normal": "건조기 사용 가능",
    "wet_clean": "웨트클리닝 가능",
    "wring": "비틀어 짜기 가능",
}

